test: resolve processes not exiting in test cases (#3259)
### Description

When using `gracefulCancel: true`, the termination signal can only be
obtained via `getCancelSignal`, but our watch implementation uses
`onExit`, which causes the process to never terminate.

```bash
Error: Build failed with 1 error:
[plugin shim]
Error: EBUSY: resource busy or locked, copyfile 'D:\shulaoda\rolldown\packages\rolldown\src\rolldown-binding.win32-x64-msvc.node' -> 'D:\shulaoda\rolldown\packages\rolldown\dist\shared\rolldown-binding.win32-x64-msvc.node'
```


![image](https://github.com/user-attachments/assets/5dfe157c-6b09-46aa-bd6f-9dae8eafe783)