feat(plugin/vite-resolve): avoid wrapping errors with napi errors (#5483)
So that the error message contains the stacktrace.

Before:
```
[Error: GenericFailure, Error: warning: Automatically externalized node built-in module "node:fs" imported from "packages/vite/src/node/__tests__/fixtures/file-url/index.html". Consider adding it to environments.custom.external if it is intended.] {
  code: 'GenericFailure'
}
```
After:
```
Error: warning: Automatically externalized node built-in module "node:fs" imported from "packages/vite/src/node/__tests__/fixtures/file-url/index.html". Consider adding it to environments.custom.external if it is intended.
    at Object.<anonymous> (/home/green/workspace/rolldown-vite/packages/vite/src/node/__tests__/resolve.spec.ts:181:17)
    at Object.mockCall (file:///home/green/workspace/rolldown-vite/node_modules/.pnpm/@vitest+spy@3.2.4/node_modules/@vitest/spy/dist/index.js:96:15)
    at Object.warn (file:///home/green/workspace/rolldown-vite/node_modules/.pnpm/tinyspy@4.0.3/node_modules/tinyspy/dist/index.js:47:103)
    at Object.warn (/home/green/workspace/rolldown-vite/packages/vite/src/node/baseEnvironment.ts:77:38)
    at onWarn (/home/green/workspace/rolldown-vite/packages/vite/src/node/plugins/resolve.ts:355:35)
```