feat(string_wizard): add `serde` feature (#3140)
When `string_wizard` is used inside `oxc`, and with `oxc_index` having
the `serde` feature enabled, feature unification breaks apart. And there
is no way to force enable a dependencie's dependency's feature. This is
the last resort :-(

```
error[E0433]: failed to resolve: use of undeclared crate or module `serde`
 --> crates/string_wizard/src/chunk.rs:5:1
  |
5 | / oxc_index::define_index_type! {
6 | |     pub struct ChunkIdx = u32;
7 | | }
  | |_^ use of undeclared crate or module `serde`
  |
  = note: this error originates in the macro `$crate::__internal_maybe_index_impl_serde` which comes from the expansion of the macro `oxc_index::define_index_type` (in Nightly builds, run with -Z macro-backtrace for more info)
```