chore(deps): bump `@napi-rs/cli` (#3459)
### Description

              > Can you check the binary diff?

I need to check later as I encountered some issues while running `just
build` and `just build native release`.

```bash
Syntax Error: Unexpected token 's', " string\n/*"... is not valid JSON
    at JSON.parse (<anonymous>)
    at file:///D:/shulaoda/rolldown/node_modules/.pnpm/@napi-rs+cli@3.0.0-alpha.65_@emnapi+runtime@1.3.1_@types+node@22.10.7_emnapi@1.3.1_node-addon-api@8.3.0_/node_modules/@napi-rs/cli/dist/utils/typegen.js:128:21
    at Array.map (<anonymous>)
    at readIntermediateTypeFile (file:///D:/shulaoda/rolldown/node_modules/.pnpm/@napi-rs+cli@3.0.0-alpha.65_@emnapi+runtime@1.3.1_@types+node@22.10.7_emnapi@1.3.1_node-addon-api@8.3.0_/node_modules/@napi-rs/cli/dist/utils/typegen.js:120:10)
    at async processTypeDef (file:///D:/shulaoda/rolldown/node_modules/.pnpm/@napi-rs+cli@3.0.0-alpha.65_@emnapi+runtime@1.3.1_@types+node@22.10.7_emnapi@1.3.1_node-addon-api@8.3.0_/node_modules/@napi-rs/cli/dist/utils/typegen.js:61:18)
    at async Builder.generateTypeDef (file:///D:/shulaoda/rolldown/node_modules/.pnpm/@napi-rs+cli@3.0.0-alpha.65_@emnapi+runtime@1.3.1_@types+node@22.10.7_emnapi@1.3.1_node-addon-api@8.3.0_/node_modules/@napi-rs/cli/dist/api/build.js:584:34)
    at async Builder.postBuild (file:///D:/shulaoda/rolldown/node_modules/.pnpm/@napi-rs+cli@3.0.0-alpha.65_@emnapi+runtime@1.3.1_@types+node@22.10.7_emnapi@1.3.1_node-addon-api@8.3.0_/node_modules/@napi-rs/cli/dist/api/build.js:450:28)
    at async BuildCommand.execute (file:///D:/shulaoda/rolldown/node_modules/.pnpm/@napi-rs+cli@3.0.0-alpha.65_@emnapi+runtime@1.3.1_@types+node@22.10.7_emnapi@1.3.1_node-addon-api@8.3.0_/node_modules/@napi-rs/cli/dist/commands/build.js:17:25)
    at async BuildCommand.validateAndExecute (D:\shulaoda\rolldown\node_modules\.pnpm\clipanion@3.2.1_typanion@3.14.0\node_modules\clipanion\lib\advanced\Command.js:73:26)
    at async Cli.run (D:\shulaoda\rolldown\node_modules\.pnpm\clipanion@3.2.1_typanion@3.14.0\node_modules\clipanion\lib\advanced\Cli.js:223:24)
 ELIFECYCLE  Command failed with exit code 1.
ERROR: "build-binding" exited with 1.
```

_Originally posted by @shulaoda in
https://github.com/rolldown/rolldown/issues/3450#issuecomment-2621126794_
            
I spent a lot of time troubleshooting and found that the issue seemed to
be related to the `@napi-rs/cli`. After updating it, the problem no
longer occurred. To prevent others from encountering the same issue,
I’ve updated it.