fix: set `order` for callable plugins (#8815)
This PR fixes the following failure:
```
 FAIL  packages/vite/src/node/ssr/runtime/__tests__/server-runtime.spec.ts > module runner initialization > oxc runtime helpers are loadable
ReferenceError: module is not defined
 ❯ eval ../../../node_modules/.pnpm/@oxc-project+runtime@0.121.0/node_modules/@oxc-project/runtime/src/helpers/taggedTemplateLiteral.js:10:1
 ❯ ESModulesEvaluator.runInlinedModule packages/vite/src/module-runner/esmEvaluator.ts:35:11
     33|     )
     34|
     35|     await initModule(
       |           ^
     36|       context[ssrModuleExportsKey],
     37|       context[ssrImportMetaKey],
 ❯ ModuleRunner.directRequest packages/vite/src/module-runner/runner.ts:430:26
 ❯ ModuleRunner.cachedRequest packages/vite/src/module-runner/runner.ts:222:33
```
https://github.com/rolldown/rolldown/actions/runs/23327388763/job/67851374703#step:7:473

This error was happening only in this repo because, in this repo, `@oxc-project/runtime` is a dependency and was resolvable from `vite-tests` directory. The internal resolver plugin is placed before the `oxcRuntimePlugin` in Vite, and because the `order` property was not set for callable plugins, the internal resolver plugin resolved `@oxc-project/runtime`.
This PR fixes that by adding `order` property for callable plugins.