chore(infra): make script `lint-repo` work on windows (#4399)
### Description

```bash
> monorepo@ lint-repo D:\shulaoda\rolldown
> pnpm run --stream --color "/^fmt|lint-spell$/"

 ELIFECYCLE  Command failed.
error: Recipe `lint-repo` failed on line 111 with exit code 1
```

<!-- This is an auto-generated comment: release notes by coderabbit.ai
-->

## Summary by CodeRabbit

- **Chores**
- Updated the formatting of the linting script in the configuration to
improve shell compatibility. No changes to functionality.

<!-- end of auto-generated comment: release notes by coderabbit.ai -->