feat(rolldown): oxc v0.97.0 (#6940)
The 3 changed files are waiting for upstream:

* https://github.com/evanw/esbuild/issues/4323

Handing the rest of the API changes to @sapphi-red

```
error[E0063]: missing field `treeshake` in initializer of `oxc_minify_napi::CompressOptions`
  --> crates/rolldown_binding/src/utils/minify_options_conversion.rs:22:3
   |
22 |   oxc_minify_napi::CompressOptions {
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `treeshake`
```