fix: fix `\0` in `JsChangedOutputs.chunks` (#3006)
### Description

After https://github.com/rolldown/rolldown/pull/2991, I now get a
following error when mutating a bundle with `chunk.modules` including
`\0`:

```
Build failed with 1 error:
Error: nul byte found in provided data at position: 0 on JsOutputChunk.modules on JsChangedOutputs.chunks
```

Since we don't consider mutating `chunk.modules` as per
https://github.com/rolldown/rolldown/pull/2993, we can pass back an
empty object, so `\0` won't get triggered when moving `JsOutputChunk`
back to rust.