feat: improve error message for `this.resolve` and `this.load` (#5596)
Made the `this.resolve` / `this.load` error message to contain the
original stacktrace.

**Old Error**:
```
[plugin test-plugin-context]
Error: Errored while resolving "./sub.js" in `this.resolve`. Got GenericFailure, Error: my error.
```

**New Error**:
```
[plugin test-plugin-context]
Error: Errored while resolving "./sub.js" in `this.resolve`.
Caused by:
  [plugin test-plugin-context]
  Error: my error
      at PluginContextImpl.resolveId (/home/green/workspace/rolldown/packages/rolldown/tests/fixtures/plugin/context/resolve/_config.ts:24:19)
      at plugin (/home/green/workspace/rolldown/packages/rolldown/dist/shared/src-_iWIzySM.mjs:2706:30)
      at plugin.<computed> (/home/green/workspace/rolldown/packages/rolldown/dist/shared/src-_iWIzySM.mjs:3404:18)
```

Related error:
https://github.com/vitejs/vite-ecosystem-ci/actions/runs/16718227301/job/47316318655#step:7:1580

depends on https://github.com/napi-rs/napi-rs/pull/2829