feat: add import path for unresolved import diagnostics (#7625)
Added a help for UNRESOLVED_IMPORT error to output the import path.
```
[UNRESOLVED_IMPORT] Error: Could not resolve '../pkg' in node_modules/.pnpm/lightningcss@1.30.2/node_modules/lightningcss/node/index.js
    ╭─[ node_modules/.pnpm/lightningcss@1.30.2/node_modules/lightningcss/node/index.js:17:28 ]
    │
 17 │   module.exports = require(`../pkg`);
    │                            ────┬───
    │                                ╰───── Module not found.
    │
    │ Help: 'node_modules/.pnpm/lightningcss@1.30.2/node_modules/lightningcss/node/index.js' is imported by the following path:
    │         - node_modules/.pnpm/lightningcss@1.30.2/node_modules/lightningcss/node/index.js
    │         - node_modules/.pnpm/lightningcss@1.30.2/node_modules/lightningcss/node/index.mjs
    │         - node_modules/.pnpm/vite@8.0.0-beta.4_@types+node@24.10.4/node_modules/vite/dist/node/chunks/node.js
    │         - node_modules/.pnpm/vite@8.0.0-beta.4_@types+node@24.10.4/node_modules/vite/dist/node/index.js
    │         - src/main.tsx
    │         - index.html
────╯
```