fix: check falsy plugin in options hook (#2670)
According to rollup's document, `config.plugins` supports falsy values.
And in rolldown's
[code](https://github.com/rolldown/rolldown/blob/f3a159b51ce05b6b513d121d279cd3b9a799544a/packages/rolldown/src/utils/normalize-plugin-option.ts#L10),
it indeed implement this feature.

However, this
[line](https://github.com/rolldown/rolldown/pull/2670/files#diff-48cd2591bdcb44946219841aaccab8eb2d54381960f9607cb7542c40f446d92eR105)
doesn't take possible falsy values into consideration, which cause's
error:
```
file:///Users/miles/Desktop/projects/xxx/node_modules/.pnpm/rolldown@https+++pkg.pr.new+rolldown@a50a3b2/node_modules/rolldown/dist/shared/src_index-Nma-IVaO.mjs:997
                if ("_parallel"in plugin) {
                               ^

TypeError: Cannot use 'in' operator to search for '_parallel' in false
    at file:///Users/miles/Desktop/projects/xxx/node_modules/.pnpm/rolldown@https+++pkg.pr.new+rolldown@a50a3b2/node_modules/rolldown/dist/shared/src_index-Nma-IVaO.mjs:997:18
    at Array.filter (<anonymous>)
    at getObjectPlugins (file:///Users/miles/Desktop/projects/xxx/node_modules/.pnpm/rolldown@https+++pkg.pr.new+rolldown@a50a3b2/node_modules/rolldown/dist/shared/src_index-Nma-IVaO.mjs:996:17)
    at PluginDriver.callOptionsHook (file:///Users/miles/Desktop/projects/xxx/node_modules/.pnpm/rolldown@https+++pkg.pr.new+rolldown@a50a3b2/node_modules/rolldown/dist/shared/src_index-Nma-IVaO.mjs:955:47)
    at createBundler (file:///Users/miles/Desktop/projects/xxx/node_modules/.pnpm/rolldown@https+++pkg.pr.new+rolldown@a50a3b2/node_modules/rolldown/dist/shared/src_index-Nma-IVaO.mjs:2642:36)
    at watch (file:///Users/miles/Desktop/projects/xxx/node_modules/.pnpm/rolldown@https+++pkg.pr.new+rolldown@a50a3b2/node_modules/rolldown/dist/shared/src_index-Nma-IVaO.mjs:2758:63)
    at file:///Users/miles/Desktop/projects/xxx/cli.js:50:25
```

This pr
- add falsy types in config plugin's declaration
- and check it at the necessary possible